esphome:
  name: homelab-watcher
  friendly_name: Homelab Watcher

substitutions:
  update_interval: "15s"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_key_Watcher

ota:
  - platform: esphome
    password: !secret ota_pw_Watcher

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Homelab-Watcher Fallback Hotspot"
    password: !secret fb_pw_Watcher


captive_portal:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

one_wire:
  - platform: gpio
    pin: GPIO4
    id: one_wire_bus

sensor:
  - platform: tmp102
    name: "HDD1"
    address: 0x48
    update_interval: ${update_interval}

  - platform: tmp102
    name: "HDD2"
    address: 0x49
    update_interval: ${update_interval}

  - platform: tmp102
    name: "HDD3"
    address: 0x4A
    update_interval: ${update_interval}

  - platform: tmp102
    name: "HDD4"
    address: 0x4B
    update_interval: ${update_interval}

  - platform: dallas_temp
    one_wire_id: one_wire_bus
    index: 0
    name: "Temperatur Netzteil"
    update_interval: ${update_interval}

  - platform: dallas_temp
    one_wire_id: one_wire_bus
    index: 1
    name: "Temperatur Innen"
    update_interval: ${update_interval}

output:
  - platform: gpio
    pin: GPIO27
    id: fan_relay_1
    inverted: true

  - platform: gpio
    pin: GPIO26
    id: fan_relay_2
    inverted: true

  - platform: gpio
    pin: GPIO25
    id: fan_relay_3
    inverted: true

  - platform: gpio
    pin: GPIO33
    id: fan_relay_4
    inverted: true

fan:
  - platform: binary
    output: fan_relay_1
    name: "Fan Netzteil"

  - platform: binary
    output: fan_relay_2
    name: "Fan Output"

  - platform: binary
    output: fan_relay_3
    name: "Fan Turm oben"

  - platform: binary
    output: fan_relay_4
    name: "Fan Turm unten"
